### ISSUE TITLE
Color Correction

### ISSUE THREAD

**Issue by RiturajGupta21** [HacOkars/Contributors#1]
Any interested people with basic knowledge of CSS are requested to edit the theme colouring style.

**Comment by MuditWadhwa** [comment]
Hi! I would like to solve this issue. Could you please elaborate the output theme that you  expect to see. I would design it according to that.

**Comment by RiturajGupta21** [comment]
Hello, Actually color combination is not specified you can go with any color palette which would make the website more attractive and if possible please fix the card position for smaller devices.

**Comment by MuditWadhwa** [comment]
Ok...Please assign this issue to me and add the hacktoberfest label to it. I would try to design it in the best possible manner.

**Comment by RiturajGupta21** [comment]
Okay.

**Comment by MuditWadhwa** [comment]
Here is a design that I just made....
![view](https://user-images.githubusercontent.com/69974521/135724844-127bae92-7900-4a6d-9768-636fb2c2fa0e.jpeg)

**Comment by MuditWadhwa** [comment]
I have also added responsiveness to the cards.

**Comment by RiturajGupta21** [comment]
Seems good please make Pull request.

**Comment by MuditWadhwa** [comment]
Ok...I have done a PR. Please accept it.

**Comment by RiturajGupta21** [comment]
Yes accepted and now with this closing the issue
